### PR TITLE
Revert "git: Add support for deepening shallow clones (#311)"

### PR DESCRIPTION
**Pull request by rohankmr414**
This reverts commit 320db9af8ba8b0046e833013504eb07c61a3573c.

### CODE REVIEW

**Comment by rohankmr414** [comment]
Fixes https://github.com/argoproj/argo-workflows/issues/9613

**Comment by sarabala1979** [comment]
@alexec Can you take quick look on this?

**Review by sarabala1979 — APPROVED** [review]
LGTM

**Comment by sarabala1979** [comment]
@alexec thanks Alex

**Comment by rohankmr414** [comment]
@alexec can you also create a release?

**Pull request merged**
